objects/Document_Type_Code_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Type_Code__c</fullName>
        <label>Type Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Check Request Form</fullName>
                    <default>true</default>
                    <label>Check Request Form</label>
                </value>
                <value>
                    <fullName>Completed Survey</fullName>
                </value>
                <value>
                    <fullName>Copy of Supplier Parts</fullName>
                </value>
                <value>
                    <fullName>Credit Card Authorization</fullName>
                </value>
                <value>
                    <fullName>Customer Correspondence</fullName>
                </value>
                <value>
                    <fullName>Customer-Specific Service Report Sign-Off</fullName>
                </value>
                <value>
                    <fullName>Damage &amp; Abuse - Before &amp; After Pictures</fullName>
                </value>
                <value>
                    <fullName>Deposit Check</fullName>
                </value>
                <value>
                    <fullName>IVR Check in and Check out (Labor)</fullName>
                </value>
                <value>
                    <fullName>Lien Waiver</fullName>
                </value>
                <value>
                    <fullName>PM Checklist completed</fullName>
                </value>
                <value>
                    <fullName>PM Failures</fullName>
                </value>
                <value>
                    <fullName>Shipping Documents</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Estimate</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Invoice</fullName>
                </value>
                <value>
                    <fullName>Vendor Correspondence</fullName>
                </value>
                <value>
                    <fullName>W-9</fullName>
                </value>
                <value>
                    <fullName>Walmart - Ready to Invoice Still needs Paperwork</fullName>
                </value>
                <value>
                    <fullName>Warranty Information</fullName>
                </value>
                <value>
                    <fullName>Work Acknowledgment Form (Service Sign-Off)</fullName>
                </value>
                <value>
                    <fullName>Note To Biller</fullName>
                </value>
                <value>
                    <fullName>Miner Sign Off Sheet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Type Code Mapping</label>
    <pluralLabel>Document Type Code Mapping</pluralLabel>
</CustomObject>

classes/UNITY_BarcodeCoverPageController.cls
public class UNITY_BarcodeCoverPageController {

    
    public WorkOrder wo {get;set;}
    public Id recordId {
        get{
            return (Id)strRecordId;
        }
        set;}
    public String strRecordId {get;
        set{            
            strRecordId = value;
        }
    }
    public String objType {
        get{
            return recordID.getSObjectType().getDescribe().getName();
        }
        set;
    }
    public String documentCode {
        get{
            Document_Type_Code_Mapping__mdt dtc = [SELECT Type_Code__c, Type__c FROM Document_Type_Code_Mapping__mdt WHERE Type__c=:documentType LIMIT 1];
            if (dtc != null)
                return dtc.Type_Code__c;
            return null;
        }
        set;
    }
    public String documentType {get;set;}
    public string objIdentifier{
        get{
            if (objType == 'WorkOrder'){
                wo = [SELECT WorkOrderNumber FROM WorkOrder WHERE ID = :recordId];
                return wo.WorkOrderNumber;
            }
            return null;
        }
        set;}
    
    public UNITY_BarcodeCoverPageController(){
        
    }
}