objects/Document_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Document_Source__c</fullName>
        <label>Document Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Uploaded</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Staging</label>
    <nameField>
        <displayFormat>Doc-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UNITY_AuraDocUploadRedirectController.cls
public class UNITY_AuraDocUploadRedirectController {
	@auraEnabled
    public static Id generateNewDocumentStaging(){
        Document_Staging__c	ds = new Document_Staging__c();
        ds.Document_Source__c = 'Community';
        insert ds;
        return ds.id;
    }
    
    @AuraEnabled
    public static List<Document_Staging__c> getDocumentStagingList(){
        return [SELECT Id, File_Name__c, Status__c, CreatedDate, DocParser_Page_Count__c, Document_Source__c, Comments__c, Name FROM Document_Staging__c WHERE OwnerID =: UserInfo.getUserId() ORDER BY CreatedDate];
    }
}