objects/Document_Type_Code_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Type_Code__c</fullName>
        <label>Type Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Check Request Form</fullName>
                    <default>true</default>
                    <label>Check Request Form</label>
                </value>
                <value>
                    <fullName>Completed Survey</fullName>
                </value>
                <value>
                    <fullName>Copy of Supplier Parts</fullName>
                </value>
                <value>
                    <fullName>Credit Card Authorization</fullName>
                </value>
                <value>
                    <fullName>Customer Correspondence</fullName>
                </value>
                <value>
                    <fullName>Customer-Specific Service Report Sign-Off</fullName>
                </value>
                <value>
                    <fullName>Damage &amp; Abuse - Before &amp; After Pictures</fullName>
                </value>
                <value>
                    <fullName>Deposit Check</fullName>
                </value>
                <value>
                    <fullName>IVR Check in and Check out (Labor)</fullName>
                </value>
                <value>
                    <fullName>Lien Waiver</fullName>
                </value>
                <value>
                    <fullName>PM Checklist completed</fullName>
                </value>
                <value>
                    <fullName>PM Failures</fullName>
                </value>
                <value>
                    <fullName>Shipping Documents</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Estimate</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Invoice</fullName>
                </value>
                <value>
                    <fullName>Vendor Correspondence</fullName>
                </value>
                <value>
                    <fullName>W-9</fullName>
                </value>
                <value>
                    <fullName>Walmart - Ready to Invoice Still needs Paperwork</fullName>
                </value>
                <value>
                    <fullName>Warranty Information</fullName>
                </value>
                <value>
                    <fullName>Work Acknowledgment Form (Service Sign-Off)</fullName>
                </value>
                <value>
                    <fullName>Note To Biller</fullName>
                </value>
                <value>
                    <fullName>Miner Sign Off Sheet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Type Code Mapping</label>
    <pluralLabel>Document Type Code Mapping</pluralLabel>
</CustomObject>

objects/UNITY_Attachment__c.object
<CustomObject>
    <description>UNITY Attachment object</description>
    <fields>
        <fullName>UNITY_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Document_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Attachment</label>
    <nameField>
        <displayFormat>Atch-{0000000000}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UNITY_AuraPrintCoverPage.cls
public class UNITY_AuraPrintCoverPage {
    
    @AuraEnabled
    public static List<String> getDocumentTypes(){
        List<string> result = new List<string>();
        System.debug('@@@getDocumentTypes:'+result);
        /*Schema.DescribeFieldResult F = UNITY_Attachment__c.UNITY_Type__c.getDescribe();
        List<PicklistEntry> entries = F.getPicklistValues();
        for (PicklistEntry ple : entries){
            result.add(ple.getLabel());
        }*/
        
        List<Document_Type_Code_Mapping__mdt> dtcList = [SELECT Type_Code__c, Type__c FROM Document_Type_Code_Mapping__mdt];
        for (Document_Type_Code_Mapping__mdt dtcm: dtcList){
             result.add(dtcm.Type__c);
        }        
        System.debug('@@@getDocumentTypes:'+result);
        return result;   
    }
    
    @AuraEnabled
    public static String getURL(){
        String result;
        
        ConnectApi.CommunityPage comList = ConnectApi.Communities.getCommunities();
        
        for (ConnectApi.Community c: comList.communities){
            if (c.Name == 'Service Provider Community'){
                result =c.siteUrl;
                continue;
            }
        }
        return result;
    }
    
}