objects/Document_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Document_Source__c</fullName>
        <label>Document Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <label>Email Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoming_Email_Address__c</fullName>
        <label>Incoming Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Uploaded</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Staging</label>
    <nameField>
        <displayFormat>Doc-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UNITY_EmailToDocumentStagingParser.cls
public class UNITY_EmailToDocumentStagingParser {
    
    public static void parse(Messaging.inboundEmail email){

        Document_Staging__c newDocStaging;

        String subject     = email.subject.trim();
        String fromAddress = email.fromAddress;
        String fromDomain  = fromAddress.split('@')[1];
        String toDomain    = email.toAddresses[0].split('@')[1];
        
         List<Attachment> attachments = new List<Attachment>();
        if (email.textAttachments != null) {
            for(Messaging.Inboundemail.TextAttachment tAttachment : email.textAttachments) {
                Attachment txtAttachment = new Attachment();
                txtAttachment.Name = tAttachment.fileName;
                txtAttachment.Body = Blob.valueOf(tAttachment.body);
                attachments.add(txtAttachment);
            }
        }
    
        if (email.binaryAttachments != null) {
            for(Messaging.Inboundemail.BinaryAttachment bAttachment : email.binaryAttachments) {
                Attachment binAttachment = new Attachment();
                binAttachment.Name = bAttachment.fileName;
                binAttachment.Body = bAttachment.body;
                attachments.add(binAttachment);
            }
        }
        
       
        newDocStaging = new Document_Staging__c( Incoming_Email_Address__c = email.fromAddress,Email_Subject__c =subject,  Status__c ='New', Document_Source__c = 'email' );
         
        insert newDocStaging;
       
         if(! attachments.isEmpty()) {
            for(Attachment att : attachments) {
                att.ParentId = newDocStaging.Id;
            }
            insert attachments;
        }
    }
}